// seed.js
const mongoose = require("mongoose");
const Doctor = require("./models/Doctor");
if (process.env.NODE_ENV != "production") {
  require("dotenv").config();
}
const LiveURL = process.env.liveUrl;
mongoose
  .connect(LiveURL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => console.log("Connected to MongoDB"))
  .catch((err) => console.error("MongoDB connection error:", err));

// Doctors data from the main.js file
const doctorsData = [
  {
    name: "Dr. Anil Kumar",
    specialization: "General Physician",
    qualification: "MBBS, MD",
    experience: 12,
    fees: 650,
    location: "Delhi",
    languages: ["Hindi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Delhi",
    gender: "Male",
    rating: 4.8,
  },
  {
    name: "Dr. Priya Sharma",
    specialization: "Internal Medicine",
    qualification: "MBBS, MD",
    experience: 8,
    fees: 800,
    location: "Mumbai",
    languages: ["English", "Hindi", "Tamil"],
    consultMode: ["Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/women/32.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Maharashtra, Mumbai",
    gender: "Female",
    rating: 4.6,
  },
  {
    name: "Dr. Rajesh Iyer",
    specialization: "General Physician",
    qualification: "MBBS, DNB",
    experience: 15,
    fees: 1200,
    location: "Chennai",
    languages: ["English", "Tamil", "Telugu"],
    consultMode: ["Hospital Visit", "Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/men/67.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Tamil Nadu, Chennai",
    gender: "Male",
    rating: 4.9,
  },
  {
    name: "Dr. Sunita Patel",
    specialization: "Internal Medicine",
    qualification: "MBBS, MD",
    experience: 10,
    fees: 950,
    location: "Ahmedabad",
    languages: ["English", "Hindi", "Gujarati"],
    consultMode: ["Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/women/54.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Gujarat, Ahmedabad",
    gender: "Female",
    rating: 4.7,
  },
  {
    name: "Dr. Vikram Mehta",
    specialization: "General Physician",
    qualification: "MBBS, MD, DM",
    experience: 20,
    fees: 1500,
    location: "Delhi",
    languages: ["English"],
    consultMode: ["Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    clinic: "Apollo 24|7 Hospital - Delhi",
    gender: "Male",
    rating: 4.9,
  },
  {
    name: "Dr. Ananya Das",
    specialization: "Internal Medicine",
    qualification: "MBBS, DNB",
    experience: 5,
    fees: 500,
    location: "Kolkata",
    languages: ["English", "Bengali", "Hindi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/women/29.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - West Bengal, Kolkata",
    gender: "Female",
    rating: 4.5,
  },
  {
    name: "Dr. Rahul Verma",
    specialization: "Cardiologist",
    qualification: "MBBS, MD, DM",
    experience: 18,
    fees: 2000,
    location: "Mumbai",
    languages: ["English", "Hindi"],
    consultMode: ["Hospital Visit", "Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/men/33.jpg",
    clinic: "Apollo 24|7 Hospital - Maharashtra, Mumbai",
    gender: "Male",
    rating: 4.9,
  },
  {
    name: "Dr. Meera Desai",
    specialization: "Pediatrician",
    qualification: "MBBS, MD",
    experience: 12,
    fees: 850,
    location: "Pune",
    languages: ["English", "Marathi", "Hindi"],
    consultMode: ["Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/women/65.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Maharashtra, Pune",
    gender: "Female",
    rating: 4.8,
  },
  {
    name: "Dr. Sanjay Gupta",
    specialization: "Neurologist",
    qualification: "MBBS, MD, DM",
    experience: 22,
    fees: 2500,
    location: "Delhi",
    languages: ["English", "Hindi"],
    consultMode: ["Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/men/78.jpg",
    clinic: "Apollo 24|7 Hospital - Delhi",
    gender: "Male",
    rating: 4.9,
  },
  {
    name: "Dr. Ritu Singhania",
    specialization: "Dermatologist",
    qualification: "MBBS, MD",
    experience: 9,
    fees: 1800,
    location: "Chandigarh",
    languages: ["English", "Hindi", "Punjabi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/women/42.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Chandigarh",
    gender: "Female",
    rating: 4.7,
  },
  {
    name: "Dr. Nikhil Joshi",
    specialization: "Orthopedic Surgeon",
    qualification: "MBBS, MS",
    experience: 16,
    fees: 1700,
    location: "Mumbai",
    languages: ["English", "Hindi"],
    consultMode: ["Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/men/52.jpg",
    clinic: "Apollo 24|7 Hospital - Maharashtra, Mumbai",
    gender: "Male",
    rating: 4.8,
  },
  {
    name: "Dr. Deepa Malhotra",
    specialization: "Gynecologist",
    qualification: "MBBS, MD",
    experience: 14,
    fees: 1200,
    location: "Delhi",
    languages: ["English", "Hindi", "Punjabi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/women/17.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Delhi",
    gender: "Female",
    rating: 4.6,
  },
  {
    name: "Dr. Vivek Sharma",
    specialization: "ENT Specialist",
    qualification: "MBBS, MS",
    experience: 11,
    fees: 900,
    location: "Jaipur",
    languages: ["English", "Hindi"],
    consultMode: ["Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/men/55.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Rajasthan, Jaipur",
    gender: "Male",
    rating: 4.5,
  },
  {
    name: "Dr. Kavita Reddy",
    specialization: "Psychiatrist",
    qualification: "MBBS, MD",
    experience: 8,
    fees: 1500,
    location: "Hyderabad",
    languages: ["English", "Telugu", "Hindi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/women/89.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Telangana, Hyderabad",
    gender: "Female",
    rating: 4.7,
  },
  {
    name: "Dr. Arjun Nair",
    specialization: "Urologist",
    qualification: "MBBS, MS, MCh",
    experience: 19,
    fees: 1800,
    location: "Kochi",
    languages: ["English", "Malayalam", "Hindi"],
    consultMode: ["Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/men/36.jpg",
    clinic: "Apollo 24|7 Hospital - Kerala, Kochi",
    gender: "Male",
    rating: 4.8,
  },
  {
    name: "Dr. Sneha Chopra",
    specialization: "Nutritionist",
    qualification: "MBBS, MSc",
    experience: 7,
    fees: 700,
    location: "Delhi",
    languages: ["English", "Hindi"],
    consultMode: ["Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/women/25.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Delhi",
    gender: "Female",
    rating: 4.6,
  },
  {
    name: "Dr. Prakash Choudhary",
    specialization: "Pulmonologist",
    qualification: "MBBS, MD",
    experience: 13,
    fees: 1400,
    location: "Jaipur",
    languages: ["English", "Hindi", "Rajasthani"],
    consultMode: ["Hospital Visit", "Online Consult"],
    imageUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    clinic: "Apollo 24|7 Hospital - Rajasthan, Jaipur",
    gender: "Male",
    rating: 4.9,
  },
  {
    name: "Dr. Neha Agarwal",
    specialization: "Ophthalmologist",
    qualification: "MBBS, MD",
    experience: 10,
    fees: 1100,
    location: "Lucknow",
    languages: ["English", "Hindi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/women/37.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Uttar Pradesh, Lucknow",
    gender: "Female",
    rating: 4.7,
  },
  {
    name: "Dr. Amit Singhal",
    specialization: "Gastroenterologist",
    qualification: "MBBS, MD, DM",
    experience: 17,
    fees: 1900,
    location: "Delhi",
    languages: ["English", "Hindi"],
    consultMode: ["Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/men/59.jpg",
    clinic: "Apollo 24|7 Hospital - Delhi",
    gender: "Male",
    rating: 4.8,
  },
  {
    name: "Dr. Divya Bhatia",
    specialization: "Endocrinologist",
    qualification: "MBBS, MD, DM",
    experience: 9,
    fees: 1600,
    location: "Chandigarh",
    languages: ["English", "Hindi", "Punjabi"],
    consultMode: ["Online Consult", "Hospital Visit"],
    imageUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    clinic: "Apollo 24|7 Virtual Clinic - Chandigarh",
    gender: "Female",
    rating: 4.6,
  },
];

async function seedDatabase() {
  try {
    // Clear existing data
    await Doctor.deleteMany({});

    // Insert new data
    await Doctor.insertMany(doctorsData);

    console.log("Database seeded successfully");
    process.exit(0);
  } catch (err) {
    console.error("Error seeding database:", err);
    process.exit(1);
  }
}

seedDatabase();
